In [1]:
from pathlib import Path
import pandas as pd
import openpyxl

def locate_root():
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "data").exists():
            return candidate
    return current

root = locate_root()
data_dir = root / "data"
metadata_dir = data_dir / "metadata"
metadata_dir.mkdir(parents=True, exist_ok=True)
xlsx_files = sorted([p for p in data_dir.rglob("*.xlsx") if p.is_file()])
len(xlsx_files)

37

In [2]:
def classify_group(path):
    folder = path.parent.name.lower()
    name = path.name.lower()
    if "healthy" in folder or "healthy" in name:
        return "healthy"
    if "defected" in folder or "defective" in folder or "defect" in name:
        return "defective"
    return "unassigned"

inventory = pd.DataFrame(
    {
        "file_name": [p.name for p in xlsx_files],
        "relative_path": [str(p.relative_to(root)) for p in xlsx_files],
        "folder": [p.parent.name for p in xlsx_files],
        "suffix": [p.suffix.lower() for p in xlsx_files],
        "size_bytes": [p.stat().st_size for p in xlsx_files],
        "group": [classify_group(p) for p in xlsx_files],
    }
)
inventory

,file_name,relative_path,folder,suffix,size_bytes,group
0,Defect15(01).xlsx,data/raw/defective/Defect15(01).xlsx,defective,.xlsx,63799916,defective
1,Defect15(02).xlsx,data/raw/defective/Defect15(02).xlsx,defective,.xlsx,6907967,defective
2,Defect15(03).xlsx,data/raw/defective/Defect15(03).xlsx,defective,.xlsx,77841167,defective
3,Defect15(04).xlsx,data/raw/defective/Defect15(04).xlsx,defective,.xlsx,40512363,defective
4,Defect15.xlsx,data/raw/defective/Defect15.xlsx,defective,.xlsx,7637,defective
5,Defect16(01).xlsx,data/raw/defective/Defect16(01).xlsx,defective,.xlsx,11509691,defective
6,Defect16(02).xlsx,data/raw/defective/Defect16(02).xlsx,defective,.xlsx,30648268,defective
7,Defect16(03).xlsx,data/raw/defective/Defect16(03).xlsx,defective,.xlsx,66812842,defective
8,Defected 1.xlsx,data/raw/defective/Defected 1.xlsx,defective,.xlsx,63801327,defective
9,Defected 2.xlsx,data/raw/defective/Defected 2.xlsx,defective,.xlsx,6908662,defective
10,Defected 3.xlsx,data/raw/defective/Defected 3.xlsx,defective,.xlsx,77842764,defective
11,Defected 4.xlsx,data/raw/defective/Defected 4.xlsx,defective,.xlsx,40513212,defective
12,Defected 5.xlsx,data/raw/defective/Defected 5.xlsx,defective,.xlsx,11510181,defective
13,Defected 6.xlsx,data/raw/defective/Defected 6.xlsx,defective,.xlsx,30648947,defective
14,Defected 7.xlsx,data/raw/defective/Defected 7.xlsx,defective,.xlsx,66814285,defective
15,Healthy 1.xlsx,data/raw/healthy/Healthy 1.xlsx,healthy,.xlsx,74918332,healthy
16,Healthy 2.xlsx,data/raw/healthy/Healthy 2.xlsx,healthy,.xlsx,13807514,healthy
17,Healthy 3.xlsx,data/raw/healthy/Healthy 3.xlsx,healthy,.xlsx,25941670,healthy
18,Healthy 4.xlsx,data/raw/healthy/Healthy 4.xlsx,healthy,.xlsx,61897162,healthy
19,Healthy 5.xlsx,data/raw/healthy/Healthy 5.xlsx,healthy,.xlsx,54412317,healthy
20,Healthy 6.xlsx,data/raw/healthy/Healthy 6.xlsx,healthy,.xlsx,159704779,healthy
21,Healthy 7.xlsx,data/raw/healthy/Healthy 7.xlsx,healthy,.xlsx,15200815,healthy
22,Healthy 8.xlsx,data/raw/healthy/Healthy 8.xlsx,healthy,.xlsx,14922444,healthy
23,Healthy 9.xlsx,data/raw/healthy/Healthy 9.xlsx,healthy,.xlsx,205901006,healthy
24,00100726.xlsx,data/raw/reference/00100726.xlsx,reference,.xlsx,15200306,unassigned
25,00101206.xlsx,data/raw/reference/00101206.xlsx,reference,.xlsx,1641150,unassigned
26,002.xlsx,data/raw/reference/002.xlsx,reference,.xlsx,4764491,unassigned
27,003.xlsx,data/raw/reference/003.xlsx,reference,.xlsx,4832612,unassigned
28,01007.xlsx,data/raw/reference/01007.xlsx,reference,.xlsx,74916751,unassigned
29,01008.xlsx,data/raw/reference/01008.xlsx,reference,.xlsx,13806840,unassigned
30,01009.xlsx,data/raw/reference/01009.xlsx,reference,.xlsx,25940618,unassigned
31,01010.xlsx,data/raw/reference/01010.xlsx,reference,.xlsx,61896539,unassigned
32,01011.xlsx,data/raw/reference/01011.xlsx,reference,.xlsx,54411039,unassigned
33,01012.xlsx,data/raw/reference/01012.xlsx,reference,.xlsx,159702393,unassigned
34,0410may.xlsx,data/raw/reference/0410may.xlsx,reference,.xlsx,14921731,unassigned
35,1138.xlsx,data/raw/reference/1138.xlsx,reference,.xlsx,433028,unassigned
36,SatFiles.xlsx,data/raw/reference/SatFiles.xlsx,reference,.xlsx,205898152,unassigned

In [3]:
def workbook_profile(path):
    try:
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        sheet_names = wb.sheetnames
        rows = []
        for sheet_name in sheet_names:
            ws = wb[sheet_name]
            rows.append(
                {
                    "file_name": path.name,
                    "sheet_name": sheet_name,
                    "max_row": ws.max_row,
                    "max_column": ws.max_column,
                }
            )
        wb.close()
        return rows
    except Exception as e:
        return [
            {
                "file_name": path.name,
                "sheet_name": None,
                "max_row": None,
                "max_column": None,
                "error": str(e),
            }
        ]

sheet_profiles = []
for path in xlsx_files:
    sheet_profiles.extend(workbook_profile(path))

sheet_inventory = pd.DataFrame(sheet_profiles)
sheet_inventory

             file_name sheet_name  max_row  max_column
0    Defect15(01).xlsx   04270743     8180         209
1    Defect15(01).xlsx   06121032    11082         208
2    Defect15(01).xlsx   06122027     2929         207
3    Defect15(01).xlsx   08180820    12432         208
4    Defect15(01).xlsx   08181312    10391         208
..                 ...        ...      ...         ...
147      SatFiles.xlsx   04192910    13113         208
148      SatFiles.xlsx   05271031    12633         208
149      SatFiles.xlsx   05110715    11503         208
150      SatFiles.xlsx   05130829    13120         208
151      SatFiles.xlsx    Sheet13    10030         208

[152 rows x 4 columns]

In [4]:
inventory_summary = (
    inventory.groupby(["group", "folder"], dropna=False)
    .agg(files=("file_name", "nunique"), total_size_bytes=("size_bytes", "sum"))
    .reset_index()
    .sort_values(["group", "folder"])
)
inventory_summary

        group     folder  files  total_size_bytes
0   defective  defective     15         596079229
1     healthy    healthy      9         626706039
2  unassigned  reference     13         638365650

In [5]:
sheet_summary = (
    sheet_inventory.groupby("file_name", dropna=False)
    .agg(
        sheets=("sheet_name", "nunique"),
        total_rows=("max_row", "sum"),
        max_rows=("max_row", "max"),
        max_columns=("max_column", "max"),
    )
    .reset_index()
    .sort_values(["max_rows", "max_columns"], ascending=[False, False])
)
sheet_summary

            file_name  sheets  total_rows  max_rows  max_columns
35     Healthy 9.xlsx      13      176280     20463          209
36      SatFiles.xlsx      13      176280     20463          209
9          01012.xlsx      10      135179     19983          208
32     Healthy 6.xlsx      10      135179     19983          208
1       00101206.xlsx       1       19983     19983           13
4          01007.xlsx       5       62310     19621          208
27     Healthy 1.xlsx       5       62310     19621          208
3            003.xlsx       5       59585     19178           13
8          01011.xlsx       4       46561     19128          208
31     Healthy 5.xlsx       4       46561     19128          208
2            002.xlsx       5       59089     19121           13
7          01010.xlsx       4       51831     18264          208
30     Healthy 4.xlsx       3       51830     18264          208
14  Defect15(03).xlsx       7       66536     15690          208
22    Defected 3.xlsx       7       66536     15690          208
19  Defect16(03).xlsx       6       57310     14684          208
26    Defected 7.xlsx       6       57310     14684          208
18  Defect16(02).xlsx       2       26302     14538          208
25    Defected 6.xlsx       2       26302     14538          208
15  Defect15(04).xlsx       3       34773     13124          208
23    Defected 4.xlsx       3       34773     13124          208
0       00100726.xlsx       1       12464     12464          208
33     Healthy 7.xlsx       1       12464     12464          208
12  Defect15(01).xlsx       6       54465     12432          209
20    Defected 1.xlsx       6       54465     12432          209
6          01009.xlsx       3       23325     11724          208
29     Healthy 3.xlsx       3       23325     11724          208
5          01008.xlsx       1       11600     11600          208
28     Healthy 2.xlsx       1       11600     11600          208
11          1138.xlsx       1       10983     10983            6
17  Defect16(01).xlsx       1        9691      9691          208
24    Defected 5.xlsx       1        9691      9691          208
10       0410may.xlsx       2       12755      9153          209
34     Healthy 8.xlsx       2       12755      9153          209
13  Defect15(02).xlsx       2        6618      4903          208
21    Defected 2.xlsx       2        6618      4903          208
16      Defect15.xlsx       1           1         1            1

In [6]:
inventory.to_csv(metadata_dir / "file_inventory.csv", index=False)
sheet_inventory.to_csv(metadata_dir / "sheet_inventory.csv", index=False)
sheet_summary.to_csv(metadata_dir / "sheet_summary.csv", index=False)

{
    "inventory": str(metadata_dir / "file_inventory.csv"),
    "sheet_inventory": str(metadata_dir / "sheet_inventory.csv"),
    "sheet_summary": str(metadata_dir / "sheet_summary.csv"),
}

{'inventory': '/home/hamza/Documents/aero-res/aircraft_fault_localization/data/metadata/file_inventory.csv',
 'sheet_inventory': '/home/hamza/Documents/aero-res/aircraft_fault_localization/data/metadata/sheet_inventory.csv',
 'sheet_summary': '/home/hamza/Documents/aero-res/aircraft_fault_localization/data/metadata/sheet_summary.csv'}